import { AxiosResponse } from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { Configuration, GreetingControllerApi } from "../api";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const config = new Configuration({
    basePath: "http://localhost:8080", // 1
    
  });
  const greetingApi = new GreetingControllerApi(config); // 2

  const [res, setRes] = useState<AxiosResponse | null>(null);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>JSON</h2>
        <p>{JSON.stringify(res)}</p>

        <h2>Data</h2>
        <p>{JSON.stringify(res?.data)}</p>

        <button
          onClick={async () => {
            const res = await greetingApi.greeting("Lukas");
            setRes(res);
          }}
          title="Test"
          value={"Test"}
        >
          Test
        </button>
      </main>
    </div>
  );
};

export default Home;
